# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eiglesia <eiglesia@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/09/10 18:41:58 by eniglesi          #+#    #+#              #
#    Updated: 2025/10/28 14:17:25 by eiglesia         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = 	ft_atoi.c		ft_bzero.c		ft_calloc.c		ft_isalnum.c	\
		ft_isalpha.c	ft_isascii.c	ft_isdigit.c	ft_isprint.c	\
		ft_itoa.c		ft_memchr.c		ft_memcmp.c		ft_memcpy.c		\
		ft_memmove.c	ft_memset.c		ft_putchar_fd.c	ft_putstr_fd.c	\
		ft_split.c		ft_strchr.c		ft_strdup.c		ft_striteri.c	\
		ft_strjoin.c	ft_strlcat.c	ft_strlcpy.c	ft_strlen.c		\
		ft_strmapi.c	ft_strncmp.c	ft_strnstr.c	ft_strrchr.c	\
		ft_strtrim.c	ft_substr.c		ft_tolower.c	ft_toupper.c	\
		ft_putendl_fd.c	ft_putnbr_fd.c	\
		ft_putchar_fd_r.c		ft_putstr_fd_r.c		ft_putnbr_fd_r.c\
		get_next_line_bonus.c	get_next_line_utils_bonus.c
OBJS = $(SRC:.c=.o)
HEADERS = libft.h get_next_line_bonus.h
NAME = libft.a
FLAGS = -Wall -Wextra -Werror 

all: $(NAME)

%.o: %.c
	cc -c $(FLAGS) $< -o $@

$(NAME): $(OBJS) $(HEADERS)
	ar -crs $(NAME) $(OBJS)

clean:
	/bin/rm -f $(OBJS)

fclean: clean
	/bin/rm -f $(NAME)
	
re: fclean all
